spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb # log4jdbc를 사용하는 H2 데이터베이스 URL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log4jdbc 드라이버 설정
    username: sa # H2 기본 사용자 이름
    password: # 비밀번호 없음
    hikari:
      pool-name: HikariCP # 히카리CP 연결풀 이름
      maximum-pool-size: 10 # 기본 연결 풀 크기
      minimum-idle: 2 # 최소한의 대기 상태의 연결
    #H2
    h2:
      console:
      enabled: true        # h2 콘솔 사용
      path: h2-console    # 접속 url e.g.) localhost:8080/h2-console
  #JPA
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_spq: true #쿼리 로그 포맷
          show_sql: true #쿼리 로그 출력
